**This notebook is an exercise in the [SQL](https://www.kaggle.com/learn/intro-to-sql) course.  You can reference the tutorial at [this link](https://www.kaggle.com/dansbecker/getting-started-with-sql-and-bigquery).**

---

# Introduction

The first test of your new data exploration skills uses data describing crime in the city of Chicago.

Before you get started, run the following cell. It sets up the automated feedback system to review your answers.

In [1]:
# Set up feedack system
from learntools.core import binder
binder.bind(globals())
from learntools.sql.ex1 import *
print("Setup Complete")

Using Kaggle's public dataset BigQuery integration.
Setup Complete

Use the next code cell to fetch the dataset.

In [2]:
from google.cloud import bigquery

# Create a "Client" object
client = bigquery.Client()

# Construct a reference to the "chicago_crime" dataset
dataset_ref = client.dataset("chicago_crime", project="bigquery-public-data")

# API request - fetch the dataset
dataset = client.get_dataset(dataset_ref)

Using Kaggle's public dataset BigQuery integration.

In [3]:
dataset_ref

DatasetReference('bigquery-public-data', 'chicago_crime')

# Exercises

### 1) Count tables in the dataset

How many tables are in the Chicago Crime dataset?

In [ ]:
# Write the code you need here to figure out the answer

In [4]:
num_tables = list(client.list_tables(dataset))  # Store the answer as num_tables and then run this cell
print(len(num_tables))
# Check your answer
q_1.check()

1

Incorrect: Incorrect value for `num_tables`: `[<google.cloud.bigquery.table.TableListItem object at 0x7f0d89650050>]`

For a hint or the solution, uncomment the appropriate line below.

In [5]:
q_1.hint()
q_1.solution()

Hint: Use the `list_tables()` method to get a list of the tables in the dataset.

Solution:
```python

# List all the tables in the "chicago_crime" dataset
tables = list(client.list_tables(dataset))

# Print number of tables in the dataset
print(len(tables))

num_tables = 1

```

### 2) Explore the table schema

How many columns in the `crime` table have `TIMESTAMP` data?

In [ ]:
# Write the code to figure out the answer

In [29]:
table_ref = dataset_ref.table("crime")
table = client.get_table(table_ref)
print(table.schema)

num_timestamp_fields = 2 # Put your answer here

# # Check your answer
q_2.check()

[SchemaField('unique_key', 'INTEGER', 'REQUIRED', None, (), None), SchemaField('case_number', 'STRING', 'NULLABLE', None, (), None), SchemaField('date', 'TIMESTAMP', 'NULLABLE', None, (), None), SchemaField('block', 'STRING', 'NULLABLE', None, (), None), SchemaField('iucr', 'STRING', 'NULLABLE', None, (), None), SchemaField('primary_type', 'STRING', 'NULLABLE', None, (), None), SchemaField('description', 'STRING', 'NULLABLE', None, (), None), SchemaField('location_description', 'STRING', 'NULLABLE', None, (), None), SchemaField('arrest', 'BOOLEAN', 'NULLABLE', None, (), None), SchemaField('domestic', 'BOOLEAN', 'NULLABLE', None, (), None), SchemaField('beat', 'INTEGER', 'NULLABLE', None, (), None), SchemaField('district', 'INTEGER', 'NULLABLE', None, (), None), SchemaField('ward', 'INTEGER', 'NULLABLE', None, (), None), SchemaField('community_area', 'INTEGER', 'NULLABLE', None, (), None), SchemaField('fbi_code', 'STRING', 'NULLABLE', None, (), None), SchemaField('x_coordinate', 'FLOAT', 'NULLABLE', None, (), None), SchemaField('y_coordinate', 'FLOAT', 'NULLABLE', None, (), None), SchemaField('year', 'INTEGER', 'NULLABLE', None, (), None), SchemaField('updated_on', 'TIMESTAMP', 'NULLABLE', None, (), None), SchemaField('latitude', 'FLOAT', 'NULLABLE', None, (), None), SchemaField('longitude', 'FLOAT', 'NULLABLE', None, (), None), SchemaField('location', 'STRING', 'NULLABLE', None, (), None)]

Correct

For a hint or the solution, uncomment the appropriate line below.

In [9]:
q_2.hint()
q_2.solution()

Hint: Begin by fetching the `crime` table. Then take a look at the table schema, and check the field type of each column.  How many times does `'TIMESTAMP'` appear?

Solution:
```python

# Construct a reference to the "crime" table
table_ref = dataset_ref.table("crime")

# API request - fetch the table
table = client.get_table(table_ref)

# Print information on all the columns in the "crime" table in the "chicago_crime" dataset
print(table.schema)

num_timestamp_fields = 2

```

### 3) Create a crime map

If you wanted to create a map with a dot at the location of each crime, what are the names of the two fields you likely need to pull out of the `crime` table to plot the crimes on a map?

In [30]:
# Write the code here to explore the data so you can find the answer
client.list_rows(table, max_results = 5).to_dataframe()

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: Cannot use bqstorage_client if max_results is set, reverting to fetching data with the tabledata.list endpoint.

,unique_key,case_number,date,block,iucr,primary_type,description,location_description,arrest,domestic,...,ward,community_area,fbi_code,x_coordinate,y_coordinate,year,updated_on,latitude,longitude,location
0,21062,HW434712,2013-09-02 07:22:00+00:00,105XX S LA SALLE ST,0110,HOMICIDE,FIRST DEGREE MURDER,PORCH,True,False,...,34,49,01A,1177144.0,1834974.0,2013,2022-09-18 04:45:51+00:00,41.702501,-87.626958,"(41.702500788, -87.626958377)"
1,1945,HH769051,2002-12-24 11:58:00+00:00,104XX S PRAIRIE AVE,0110,HOMICIDE,FIRST DEGREE MURDER,HOUSE,True,True,...,9,49,01A,1179761.0,1835736.0,2002,2022-08-31 04:51:30+00:00,41.704533,-87.617352,"(41.704532517, -87.61735248)"
2,21081,HW448778,2013-09-12 02:59:00+00:00,001XX W 104TH PL,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,...,34,49,01A,1177286.0,1835665.0,2013,2022-09-18 04:45:51+00:00,41.704394,-87.626418,"(41.704393792, -87.626417643)"
3,4872,HP683603,2008-12-15 10:18:00+00:00,105XX S MICHIGAN AVE,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,False,...,9,49,01A,1178842.0,1834986.0,2008,2022-09-18 04:45:51+00:00,41.702495,-87.620740,"(41.702495331, -87.620740424)"
4,21778,HY177958,2015-03-09 07:41:00+00:00,002XX W 105TH ST,0110,HOMICIDE,FIRST DEGREE MURDER,STREET,True,False,...,34,49,01A,1176504.0,1835313.0,2015,2022-09-18 04:45:51+00:00,41.703445,-87.629292,"(41.703445434, -87.629291729)"

In [34]:
fields_for_plotting = ['x_coordinate','y_coordinate' ] # Put your answers here

# Check your answer
q_3.check()

`'latitude'` and `'longitude'` would be better and more standard than `'x_coordinate'` and `'y_coordinate'`, but this might work.

Correct

For a hint or the solution, uncomment the appropriate line below.

In [33]:
q_3.hint()
q_3.solution()

Hint: Look at the table schema.  There are a couple options, but two of the fields are things commonly used to plot on maps. Both are `'FLOAT'` types. Use quotes around the field names in your answer.

Solution:
```python
fields_for_plotting = ['latitude', 'longitude']
```

Thinking about the question above, there are a few columns that appear to have geographic data. Look at a few values (with the `list_rows()` command) to see if you can determine their relationship.  Two columns will still be hard to interpret. But it should be obvious how the `location` column relates to `latitude` and `longitude`.

In [ ]:
# Scratch space for your code

# Keep going

You've looked at the schema, but you haven't yet done anything exciting with the data itself. Things get more interesting when you get to the data, so keep going to **[write your first SQL query](https://www.kaggle.com/dansbecker/select-from-where).**

---




*Have questions or comments? Visit the [course discussion forum](https://www.kaggle.com/learn/intro-to-sql/discussion) to chat with other learners.*